//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.ObjectModel;
    /// <summary>
    /// Describes orders sql table, includes info about client and employee, includes products associated to order.
    /// </summary>
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Ord_Prod = new ObservableCollection<Ord_Prod>();
        }
    
        public int order_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime order_date { get; set; }
        public short order_employee { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Ord_Prod> Ord_Prod { get; set; }
    }
}
